//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards.Infrastructure.Localization {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flashcards.Infrastructure.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add flashcards.
        /// </summary>
        public static string AddFlashcards {
            get {
                return ResourceManager.GetString("AddFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add lesson.
        /// </summary>
        public static string AddLesson {
            get {
                return ResourceManager.GetString("AddLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking mode.
        /// </summary>
        public static string AskingMode {
            get {
                return ResourceManager.GetString("AskingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string AskingMode_Back {
            get {
                return ResourceManager.GetString("AskingMode_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string AskingMode_Front {
            get {
                return ResourceManager.GetString("AskingMode_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string AskingMode_Random {
            get {
                return ResourceManager.GetString("AskingMode_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask in repetititons.
        /// </summary>
        public static string AskInRepetitions {
            get {
                return ResourceManager.GetString("AskInRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose flashcards back language.
        /// </summary>
        public static string ChooseBackLanguage {
            get {
                return ResourceManager.GetString("ChooseBackLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose flashcards front language.
        /// </summary>
        public static string ChooseFrontLanguage {
            get {
                return ResourceManager.GetString("ChooseFrontLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Lesson.
        /// </summary>
        public static string DeleteLesson {
            get {
                return ResourceManager.GetString("DeleteLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t know.
        /// </summary>
        public static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of session.
        /// </summary>
        public static string EndOfSession {
            get {
                return ResourceManager.GetString("EndOfSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcard cannot be empty.
        /// </summary>
        public static string FlashcardCannotBeEmpty {
            get {
                return ResourceManager.GetString("FlashcardCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards.
        /// </summary>
        public static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards:.
        /// </summary>
        public static string Flashcards_Colon {
            get {
                return ResourceManager.GetString("Flashcards_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards for today: {0}.
        /// </summary>
        public static string FlashcardsForToday {
            get {
                return ResourceManager.GetString("FlashcardsForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert lesson name.
        /// </summary>
        public static string InsertLessonName {
            get {
                return ResourceManager.GetString("InsertLessonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew.
        /// </summary>
        public static string Know {
            get {
                return ResourceManager.GetString("Know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known.
        /// </summary>
        public static string Known {
            get {
                return ResourceManager.GetString("Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson name.
        /// </summary>
        public static string LessonName {
            get {
                return ResourceManager.GetString("LessonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum flashcards in single repetition.
        /// </summary>
        public static string MaximumFlashcardsInSingleRepetition {
            get {
                return ResourceManager.GetString("MaximumFlashcardsInSingleRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next flashcard.
        /// </summary>
        public static string NextFlashcard {
            get {
                return ResourceManager.GetString("NextFlashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flashcards.
        /// </summary>
        public static string NoFlashcards {
            get {
                return ResourceManager.GetString("NoFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repetition flashcards for today.
        /// </summary>
        public static string NoRepetitionFlashcardsForToday {
            get {
                return ResourceManager.GetString("NoRepetitionFlashcardsForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification time.
        /// </summary>
        public static string NotificationTime {
            get {
                return ResourceManager.GetString("NotificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        public static string Repetition {
            get {
                return ResourceManager.GetString("Repetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition asking mode.
        /// </summary>
        public static string RepetitionAskingMode {
            get {
                return ResourceManager.GetString("RepetitionAskingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        public static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition streak: {0} days.
        /// </summary>
        public static string RepetitionStreak {
            get {
                return ResourceManager.GetString("RepetitionStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle flashcards.
        /// </summary>
        public static string ShuffleFlashcards {
            get {
                return ResourceManager.GetString("ShuffleFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
